### ISSUE TITLE
wondering if there is a updation about the model or the update frequency

### ISSUE THREAD

**Issue by gkk-2000** [witch-team/witchmodel#2]
Hi,WITCH team.

Thanks for your great contribution to WICTH 5.2.I am wondering if there is a updation about the model or the update frequency.

**Comment by lolow** [comment]
Thank you for your interest. Currently, we don't have any updates planned due to resource constraints in packaging a new release. However, we do offer access to a development version for specific research or project needs, with a focus on academic collaborations. If this interests you, please provide details about your purpose, and we'll see how we can assist.

**Comment by gkk-2000** [comment]
Thanks for your early reply,so how can I provide my details?Is this mail (info@witchmodel.org) ok?
